### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by alanvardy** [CorneliaKelinske/ex_robo_cop#38]
I think that the rust dependencies might need to be updated?

```
#0 46.03 ==> ex_robo_cop
#0 46.03 Compiling 3 files (.ex)
#0 46.38     Updating crates.io index
#0 56.03 Compiling lib/ex_robo_cop/rust_captcha.ex (it's taking more than 10s)
#0 182.5 error: failed to select a version for the requirement `once_cell = "=1.18.0"`
#0 182.5 candidate versions found which didn't match: 1.17.2, 1.17.1, 1.17.0, ...
#0 182.5 location searched: crates.io index
#0 182.5 required by package `ahash v0.8.3`
#0 182.5     ... which is depended on by `hashbrown v0.13.2`
#0 182.5     ... which is depended on by `fallible_collections v0.4.7`
#0 182.5     ... which is depended on by `lodepng v3.7.2`
#0 182.5     ... which is depended on by `captcha v0.0.8`
#0 182.5     ... which is depended on by `rustcaptcha v0.1.0 (/app/deps/ex_robo_cop/native/rustcaptcha)`
#0 182.5
#0 182.5 == Compilation error in file lib/ex_robo_cop/rust_captcha.ex ==
#0 182.5 ** (RuntimeError) calling `cargo metadata` failed.
#0 182.5
#0 182.5     (rustler 0.29.1) lib/rustler/compiler/config.ex:88: Rustler.Compiler.Config.metadata!/1
#0 182.5     (rustler 0.29.1) lib/rustler/compiler/config.ex:70: Rustler.Compiler.Config.build/1
#0 182.5     (rustler 0.29.1) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
#0 182.5     lib/ex_robo_cop/rust_captcha.ex:6: (module)
#0 182.5 could not compile dependency :ex_robo_cop, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_robo_cop", update it with "mix deps.update ex_robo_cop" or clean it with "mix deps.clean ex_robo_cop"
------
Error: failed to fetch an image or build from source: error building: failed to solve: executor failed running [/bin/sh -c mix deps.compile]: exit code: 1
```

**Comment by CorneliaKelinske** [comment]
The latest release (0.1.4) updates all dependencies.

if deploy with fly.io still fails, you might have to change the way you install rust in your docker file.
I updated my dockerfile with latest Elixir version etc. and install rust via a curl command:
https://github.com/CorneliaKelinske/the_brogrammer/blob/main/Dockerfile
